wee={platform:{}};
wee.platform.okbutton="确 定";
wee.platform.closebutton="关 闭";
wee.platform.cancelbutton="取 消";
wee.platform.popDefaultTitle="提 示"
wee.platform.errorMsgTitle="系统异常";
wee.platform.timeout="您的会话已超时，请重新登录！";


sipo={};
//管理子系统
sipo.sysmgr={};
sipo.sysmgr.selectone="请选择一条记录！"
sipo.sysmgr.selectonemore="请选择至少一条记录！"
sipo.sysmgr.connotdeleteroot="这是根节点，不能删除！"
sipo.sysmgr.submit="确 定";
sipo.sysmgr.cancel="取 消";
sipo.sysmgr.close="关 闭";
sipo.sysmgr.back="上一步";
sipo.sysmgr.next="下一步";
//+++++++++++++资源管理 begin++++++++++++++++++++
sipo.sysmgr.resource={};
sipo.sysmgr.resource.resourcename=" 资源名称："
sipo.sysmgr.resource.resourcedescribe="\n 资源描述："
sipo.sysmgr.resource.resourceurl="\n 资源链接："
sipo.sysmgr.resource.resourceid="\n 资源ID："
sipo.sysmgr.resource.resourcenourl="未链接"
sipo.sysmgr.resource.resourcenoleaf="非叶子节点"
sipo.sysmgr.resource.newresource="新增资源信息"
sipo.sysmgr.resource.editresource="修改资源信息"
sipo.sysmgr.resource.leafresourcenoadd="叶子资源不能创建新资源！"
sipo.sysmgr.resource.resourceidexist="该资源ID已存在，请重新输入"
sipo.sysmgr.resource.resourceidneeded="请填写资源ID！"
sipo.sysmgr.resource.resourceidonlyec="资源ID只能是英文、数字和下划线的组合！"
sipo.sysmgr.resource.resourcetitleonlyecn="资源名称只能是中文、英文和数字的组合！"
sipo.sysmgr.resource.resourcedescribeonlyecn="描述信息只能是中文、英文和数字的组合！"
sipo.sysmgr.resource.addresourcesuccess="新增资源成功！"
sipo.sysmgr.resource.editresourcesuccess="修改资源成功！"
sipo.sysmgr.resource.deleteresourcesuccess="删除资源成功！"
sipo.sysmgr.resource.areyousuretodeleteresource="您确定要删除此资源分支？"
sipo.sysmgr.resource.renameresourceid="数据库中已存在该资源ID，请重新命名！或者请点击【取消】"
sipo.sysmgr.resource.specialcharacter="只能输入中文、英文、数字三者的组合！";
sipo.sysmgr.resource.specialcharacteronlyennum="只能输入英文、数字的组合！";

sipo.sysmgr.resource.editurl="修改"
sipo.sysmgr.resource.deleteurl="删除"
sipo.sysmgr.resource.addurlsuccess="新增URL成功！"
sipo.sysmgr.resource.editurlsuccess="修改URL成功！"
sipo.sysmgr.resource.deleteurlsuccess="删除URL成功！"
sipo.sysmgr.resource.areyousuretodeleteurl="您确定要删除URL？"
sipo.sysmgr.resource.urldescribeonlyecn="URL描述只能是中文、英文和数字的组合！"
sipo.sysmgr.resource.canbindurllist="可供绑定url列表"
sipo.sysmgr.resource.urliserror="URL输入错误！"
//+++++++++++++++资源管理 end++++++++++++++++++++++++


//菜单
sipo.sysmgr.menu={};
sipo.sysmgr.menu.specialcharacter="只能是中文、英文、数字三者的组合！";
sipo.sysmgr.menu.namespecialcharacter ="菜单名称只能是中文、英文、数字三者的组合！";
sipo.sysmgr.menu.descriptionspecialcharacter="描述信息只能是中文、英文和数字的组合！";
sipo.sysmgr.menu.addsuccess="新建菜单项成功！";
sipo.sysmgr.menu.modifysuccess="修改菜单项成功！";
sipo.sysmgr.menu.onlyleafresource="只能绑定叶子资源！";
sipo.sysmgr.menu.cannotnewnode="该节点已为叶子节点,不能创建子节点！";
sipo.sysmgr.menu.cannotdeleteroot="不能删除菜单树的根节点！"
sipo.sysmgr.menu.deletesuccess="删除菜单项成功！";
sipo.sysmgr.menu.cannotbindresource="该节点为目录节点,不能绑定资源！";
sipo.sysmgr.menu.pleasechooseresource="请选择资源！";
sipo.sysmgr.menu.bindsuccess="绑定资源成功！";
sipo.sysmgr.menu.notuseunbind="该菜单未绑定资源,不需撤销！";
sipo.sysmgr.menu.unbindsuccess="撤销资源绑定成功！";
sipo.sysmgr.menu.confirmdelete="您确定要删除所选菜单项？";
sipo.sysmgr.menu.confirmunbind="您确定要撤销当前绑定的资源吗？";
sipo.sysmgr.menu.add="新建菜单项";
sipo.sysmgr.menu.edit="修改菜单项";
sipo.sysmgr.menu.resource="待绑定资源";
sipo.sysmgr.menu.menuname="菜单名称";
sipo.sysmgr.menu.menuurl="对应导航";
sipo.sysmgr.menu.menudescription="菜单描述";
sipo.sysmgr.menu.menuresource="绑定资源";
sipo.sysmgr.menu.nomenu="对不起！您没有可看的菜单,请联系系统管理员！";
//用户
sipo.sysmgr.user={};

sipo.sysmgr.user.text_addunit="新增组织机构";
sipo.sysmgr.user.text_editunit="修改组织机构";
sipo.sysmgr.user.text_chooserole="选择角色";
sipo.sysmgr.user.text_chooseunit="选择组织机构";

sipo.sysmgr.user.text_userlist="用户列表";
sipo.sysmgr.user.text_userdetail="用户详细信息";
sipo.sysmgr.user.text_useradd="用户添加";
sipo.sysmgr.user.text_useredit="用户修改";
sipo.sysmgr.user.text_resetpwd="密码重置";
sipo.sysmgr.user.text_ok="确定";
sipo.sysmgr.user.text_cancel="取消";
sipo.sysmgr.user.text_changerole="角色修改";
sipo.sysmgr.user.text_male="男";
sipo.sysmgr.user.text_female="女";
sipo.sysmgr.user.text_enable="启用";
sipo.sysmgr.user.text_disable="禁用";
sipo.sysmgr.user.text_select="--请选择--";

sipo.sysmgr.user.orgnamespecialcharacter="组织机构名称只能是中文、英文或者二者的组合！";
sipo.sysmgr.user.orgdescriptionspecialcharacter="描述信息只能是中文、英文和数字的组合！";
sipo.sysmgr.user.orgnameexist="组织机构名称已存在！";
sipo.sysmgr.user.orgaddsuccess="新增组织机构成功！";
sipo.sysmgr.user.orgmodifysuccess="修改组织机构成功！";
sipo.sysmgr.user.adminoperate="非超级管理员不能进行此操作！";
sipo.sysmgr.user.cannoteditownorg="不能修改本用户所属组织机构信息！";
sipo.sysmgr.user.cannotdelownorg="不能删除本用户所属组织机构信息！";
sipo.sysmgr.user.cannotdeldefaultorg="不能删除系统默认的组织机构！";
sipo.sysmgr.user.cannotdelorgroot="组织机构树根节点不能删除！";
sipo.sysmgr.user.confirmdelorg="您确定要删除所选组织机构吗？";
sipo.sysmgr.user.orgdelsuccess="删除组织机构成功！";
sipo.sysmgr.user.orgmovesuccess="移动组织机构成功！";

sipo.sysmgr.user.pleasechooseonlyone="请选择一条记录！";
sipo.sysmgr.user.pleasechooseoneormore="请至少选择一条记录！";
sipo.sysmgr.user.confirmdeluser="确定要删除所选用户？";
sipo.sysmgr.user.userdelsuccess="删除用户成功！";
sipo.sysmgr.user.usernamespecialcharacter="用户名只能是英文和数字的组合！";
sipo.sysmgr.user.fullnamespecialcharacter="姓名只能是中文、英文和·的组合！";
sipo.sysmgr.user.startdateerror="起始日期格式不正确！";
sipo.sysmgr.user.enddateerror="截止日期格式不正确！";
sipo.sysmgr.user.comparedate="起始日期不能晚于截止日期！";
sipo.sysmgr.user.specialcharacter="只能是中文、英文和数字的组合！";
sipo.sysmgr.user.companynamespecialcharacter="单位公司名称只能是中文、英文和数字的组合！";
sipo.sysmgr.user.confirmuserenable="确定要启用所选用户？";
sipo.sysmgr.user.userenablesuccess="启用用户成功！";
sipo.sysmgr.user.confirmuserdisable="确定要禁用所选用户？";
sipo.sysmgr.user.userdisablesuccess="禁用用户成功！";
sipo.sysmgr.user.pwdresetsuccess="重置用户密码成功！";
sipo.sysmgr.user.rolechangesuccess="修改用户角色成功！";
sipo.sysmgr.user.cannotchooseroleroot="不能选择角色树根节点！";
sipo.sysmgr.user.usernameexist="用户名已存在！";
sipo.sysmgr.user.fullnamecheck="姓名只能以中文/英文开头由中文、英文和·的组合！";
sipo.sysmgr.user.addrspecialcharacter="详细地址只能是中文、英文和数字的组合！";
sipo.sysmgr.user.remarkspecialcharacter="备注信息只能是中文、英文和数字的组合！";
sipo.sysmgr.user.confirmaddnorole="不指定角色的用户将无法登录系统,确定添加吗？";
sipo.sysmgr.user.useraddsuccess="添加用户成功！";
sipo.sysmgr.user.pleasechooseorg="请选择组织结构！";
sipo.sysmgr.user.cannotchooseorgroot="不能选择组织机构根节点！";
sipo.sysmgr.user.usermodifysuccess="修改用户成功！";
//角色
sipo.sysmgr.role={};
sipo.sysmgr.role.specialcharacter="只能是中文、英文和数字的组合！";
sipo.sysmgr.role.rolenamespecialcharacter="角色名称只能是中文、英文和数字的组合！";
sipo.sysmgr.role.roledescriptionspecialcharacter="角色描述只能是中文、英文和数字的组合！";
sipo.sysmgr.role.roleaddsuccess="添加角色成功！";
sipo.sysmgr.role.roleaddfailure="添加角色失败！";
sipo.sysmgr.role.rolemodifysuccess="修改角色成功！";
sipo.sysmgr.role.rolemodifyfailure="修改角色失败！";
sipo.sysmgr.role.rootcannotaddrole="根节点下不能新建角色！";
sipo.sysmgr.role.anonyrolecannotaddrole="匿名用户角色下不能创建子角色！";
sipo.sysmgr.role.cannotedithighestrole="不能对本用户所拥有的最高角色进行修改！";
sipo.sysmgr.role.cannoteditroot="不能修改根节点！";
sipo.sysmgr.role.cannoteditanonyrole="不能修改匿名用户角色！";
sipo.sysmgr.role.cannotdelhighestrole="不能对本用户所拥有的最高角色进行删除！";
sipo.sysmgr.role.cannotdelroot="不能删除根节点！";
sipo.sysmgr.role.cannotdeldefaultrole="不能删除系统默认的角色！";
sipo.sysmgr.role.cannotdelanonyrole="不能删除匿名用户角色！";
sipo.sysmgr.role.confirmdelrolehaschild="此节点拥有子节点，点击确定将删除全部子节点！";
sipo.sysmgr.role.confirmdelrolenochild="你确定要删除吗？";
sipo.sysmgr.role.roledelsuccess="删除角色成功！";
sipo.sysmgr.role.roledelfailure="删除角色失败！";
sipo.sysmgr.role.usernamecheck="用户名只能是中文、英文和数字！";
sipo.sysmgr.role.fullnamecheck="姓名只能是中文、英文和数字！";
sipo.sysmgr.role.confirmuserdel="您确定要删除选中的用户吗？";
sipo.sysmgr.role.roleuserdelsuccess="当前角色下用户删除成功！";
sipo.sysmgr.role.pleasechooseoneormore="请选择至少一条记录！";
sipo.sysmgr.role.anonyrolecannotadduser="不能为匿名角色添加用户！";
sipo.sysmgr.role.cannotchooseroot="不能选择根节点！";
sipo.sysmgr.role.roleuseraddsuccess="为选中角色添加用户成功！";
sipo.sysmgr.role.companynamespecialcharacter="公司名称只能是中文、英文和数字！";
sipo.sysmgr.role.startdateerror="起始日期格式不正确！";
sipo.sysmgr.role.enddateerror="截止日期格式不正确！";
sipo.sysmgr.role.comparedate="起始日期不能小于截止日期！";
sipo.sysmgr.role.pleasechooseonlyonerole="请选择一个角色！";
sipo.sysmgr.role.applypermitsuccess="申请通过！";
sipo.sysmgr.role.pleasechooseorg="请选择一个组织机构！";
sipo.sysmgr.role.applypermitalready="该申请已经通过！";
sipo.sysmgr.role.confirmpermit="您确定要审批通过吗？";
sipo.sysmgr.role.modifypermitsuccess="修改通过！";
sipo.sysmgr.role.pleasechooseonlyone="请选择一条数据！";
sipo.sysmgr.role.confirmdel="你确定要删除选中信息吗？";
sipo.sysmgr.role.delsuccess="删除成功！";
sipo.sysmgr.role.pass="通过";
sipo.sysmgr.role.nopass="未通过";
sipo.sysmgr.role.apply="申请";
sipo.sysmgr.role.modify="修改";
sipo.sysmgr.role.business="行业用户";
sipo.sysmgr.role.advance="高级用户";
sipo.sysmgr.role.detail="详细信息";
sipo.sysmgr.role.addrole="新增角色";
sipo.sysmgr.role.editrole="修改角色";
sipo.sysmgr.role.rolenameexist="角色名称已存在！";
sipo.sysmgr.role.rolemovesuccess="移动角色成功！";

//权限管理
sipo.sysmgr.privilege={};
sipo.sysmgr.privilege.novalidrole="该角色为无效角色,请选择其他角色！";
sipo.sysmgr.privilege.pleasechooserole="请先选择某个角色,然后再选择相应的资源！";
sipo.sysmgr.privilege.cannotsave="该角色没有相关资源不能保存！";
sipo.sysmgr.privilege.saveprivilegesuccess="保存权限成功！";
sipo.sysmgr.privilege.saveprivilegefailure="保存权限失败！";

//+++++++++++++用户日志管理 begin+++++++++++++++++++++
sipo.sysmgr.bizlog={};
sipo.sysmgr.bizlog.look="查看"
sipo.sysmgr.bizlog.dele="删除"
sipo.sysmgr.bizlog.usernameonlyen="用户名只能是英文和数字的组合"
sipo.sysmgr.bizlog.iponlynum="IP只能是数字和.的组合"
sipo.sysmgr.bizlog.rolenameonlyecn="角色名称只能是中文、英文和数字的组合"
sipo.sysmgr.bizlog.begindateerror="起始日期格式不正确！"
sipo.sysmgr.bizlog.enddateerror="截止日期格式不正确！"
sipo.sysmgr.bizlog.dateerror="起始日期不能晚于截止日期！"
sipo.sysmgr.bizlog.areyousuretodeletebizlogs="您确定要删除所选用户操作日志?"
sipo.sysmgr.bizlog.areyousuretodeletethisbizlog="您确定要删除这篇用户操作日志?"
sipo.sysmgr.bizlog.deletebizlogsuccess="日志删除成功！"
sipo.sysmgr.bizlog.deletebizlogerror="日志删除失败！"
sipo.sysmgr.bizlog.exportbizlog="条件导出日志"
sipo.sysmgr.bizlog.bizlogdetail="操作日志详细信息"
sipo.sysmgr.bizlog.dateerror="日期格式不正确！"
sipo.sysmgr.bizlog.areyousuretodeleteallbizlogs="您确定要删除全部操作日志？"
//+++++++++++++用户日志管理 end+++++++++++++++++++++++