DROP TABLE WEE_ORG_ACCOUNT ;
DROP TABLE WEE_AUTH_RESOURCE ;
DROP TABLE WEE_AUTH_ROLE ;
DROP TABLE WEE_AUTH_M_ROLE_RESOURCE ;
DROP TABLE WEE_ORG_USER ;
DROP TABLE WEE_AUTH_M_USER_ROLE ;
DROP TABLE WEE_ORG_UNIT ;
DROP TABLE WEE_ORG_M_USER_UNIT ;

CREATE TABLE WEE_ORG_ACCOUNT  (
   ACCOUNT_ID           VARCHAR(32) NOT NULL,
   USER_ID              VARCHAR(32),
   USERNAME             VARCHAR(128),
   PASSWORD             VARCHAR(128),
   REGISTE_DATE         DATE,
   EXPIRED_DATE         DATE,
   ENABLED              VARCHAR(1),
   LOCKED               VARCHAR(1),
   DESCRIPTION          VARCHAR(2048),
   QUESTION             VARCHAR(1000),
   ANSWER               VARCHAR(1000)
);

ALTER TABLE WEE_ORG_ACCOUNT
  ADD CONSTRAINT PK_WEE_ORG_ACCOUNT_KEY PRIMARY KEY (ACCOUNT_ID);


CREATE TABLE WEE_AUTH_RESOURCE  (
   RESOURCE_ID          VARCHAR(32) NOT NULL,
   TITLE                VARCHAR(256),
   PARENT_ID            VARCHAR(32),
   IS_LEAF              VARCHAR(1),
   RESOURCE_TYPE        VARCHAR(2),
   DESCRIPTION          VARCHAR(256)
);

ALTER TABLE WEE_AUTH_RESOURCE
  ADD CONSTRAINT PK_WEE_AUTH_RESOURCE PRIMARY KEY (RESOURCE_ID);

  
CREATE TABLE WEE_AUTH_ROLE
(
  ROLE_ID     VARCHAR(32) NOT NULL,
  ROLE_NAME   VARCHAR(128),
  DESCRIPTION VARCHAR(128),
  PARENT_ID   VARCHAR(32),
  IS_LEAF     VARCHAR(10)
);

ALTER TABLE WEE_AUTH_ROLE
  ADD CONSTRAINT PK_WEE_AUTH_ROLE PRIMARY KEY (ROLE_ID);

CREATE TABLE WEE_AUTH_M_ROLE_RESOURCE
(
  ROLE_ID     VARCHAR(32) NOT NULL,
  RESOURCE_ID VARCHAR(32) NOT NULL
);

ALTER TABLE WEE_AUTH_M_ROLE_RESOURCE
  ADD CONSTRAINT PK_WEE_MAPP_RES_AND_ROLE PRIMARY KEY (ROLE_ID, RESOURCE_ID);


CREATE TABLE WEE_ORG_USER
(
  USER_ID     VARCHAR(32) NOT NULL,
  FULL_NAME   VARCHAR(128) NOT NULL,
  SEX         VARCHAR(1),
  TEL         VARCHAR(20),
  EMAIL       VARCHAR(128),
  DESCRIPTION VARCHAR(1024)
);

ALTER TABLE WEE_ORG_USER
  ADD CONSTRAINT PK_WEE_ORG_USER PRIMARY KEY (USER_ID);


CREATE TABLE WEE_AUTH_M_USER_ROLE
(
  ROLE_ID VARCHAR(32),
  USER_ID VARCHAR(32)
);

ALTER TABLE WEE_AUTH_M_USER_ROLE
  ADD CONSTRAINT KEY_USER_ROLE UNIQUE (ROLE_ID, USER_ID);


CREATE TABLE WEE_ORG_UNIT
(
  UNIT_ID     VARCHAR(32) NOT NULL,
  UNIT_NAME   VARCHAR(128),
  DESCRIPTION VARCHAR(128),
  PARENT_ID   VARCHAR(32),
  IS_LEAF     VARCHAR(10)
);
  
ALTER TABLE WEE_ORG_UNIT
  ADD CONSTRAINT PK_WEE_ORG_UNIT PRIMARY KEY (UNIT_ID);


CREATE TABLE WEE_ORG_M_USER_UNIT
(
  UNIT_ID VARCHAR(32),
  USER_ID VARCHAR(32)
);

ALTER TABLE WEE_ORG_M_USER_UNIT
  ADD CONSTRAINT PK_KEY_USER_UNIT_MAPPING UNIQUE (UNIT_ID, USER_ID);

CREATE TABLE WEE_AUTH_URL
(
  URL_ID      VARCHAR(32) NOT NULL,
  CONTENT VARCHAR(256)
);

ALTER TABLE WEE_AUTH_URL
  ADD CONSTRAINT PK_WEE_AUTH_URL_ID PRIMARY KEY (URL_ID);
  
CREATE TABLE WEE_AUTH_M_RESOURCE_URL
(
  RESOURCE_ID VARCHAR(32) NOT NULL,
  URL_ID      VARCHAR(32) NOT NULL
);
