create table PS_CODE
(
  ID VARCHAR(32) ,
  CODE_TYPE VARCHAR(32) ,
  TYPE_NAME VARCHAR(128),
  USER_ID   VARCHAR(32),
  OPERDATE  DATE,
  REMARK    VARCHAR(2000) 
);

ALTER TABLE PS_CODE
  ADD CONSTRAINT PK_PS_CODE PRIMARY KEY (ID);
  
create table PS_CODE_SUB
(
  ID  VARCHAR(32),
  CODE_NAME  VARCHAR(64),
  CODE_VALUE VARCHAR(256),
  USER_ID    VARCHAR(32),
  OPERDATE   DATE,
  SORT_ORDER  INTEGER
);

ALTER TABLE PS_CODE_SUB
  ADD CONSTRAINT PK_PS_CODE_SUB PRIMARY KEY (ID, CODE_NAME);
